services:
  - type: web
    name: dentcode
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
      - key: LANG
        value: en_US.UTF-8
      - key: LC_ALL
        value: en_US.UTF-8
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        value: https://dentcode.onrender.com
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        value: dentcode-verify
    healthCheckPath: /api/health
